version: "3.8"

services:
  mariadb:
    image: mariadb:11.1.2
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    env_file:
      - docker.env
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    env_file:
      - docker.env
    ports:
      - 9200:80

  # nodejs:
  #   build:
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mariadb
  #   ports:
  #     - 3000:3000
  #   restart: always
