version: "3.8"

services:
  mariadb:
    image: mariadb:11.1.2
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - m321_project_mariadb:/var/lib/mysql
    restart: always
    env_file:
      - docker.env
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    env_file:
      - docker.env
    ports:
      - 9200:80

volumes:
  m321_project_mariadb:
